version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pswd12345
      POSTGRES_DB: postgres
    volumes:
      - ./file_storage:/file_storage

  data_ingestion:
    build:
      context: .
      dockerfile: data_ingestion.Dockerfile
    volumes:
      - ./file_storage:/file_storage
      - ./data_ingestion:/data_ingestion
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./file_storage:/file_storage
      - ./api/app:/api/app
    depends_on:
      - postgres
volumes:
  file_storage: