version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pswd12345
      POSTGRES_DB: postgres
    volumes:
      # - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgres-data:/var/lib/postgresql/data
      # - ./app/file_storage:/file_storage

  migration_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - postgres
