version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pswd12345
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data